name: ingest-nightly
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python src/ingest/fetch_standings.py
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          BASE_URL: ${{ vars.BASE_URL }}
          LEAGUE_ID: ${{ vars.LEAGUE_ID }}
          SEASON: ${{ vars.SEASON }}
